import { ref, computed, watch } from 'vue'
import api from '../../api.js'
import { useRulesReview } from '../../shared/RulesReviewMixin.js'

export default function AutoGeneratedRulesReviewJS(props, { emit }) {
  // Use shared rules review functionality
  const {
    showSnack,
    snackMessage,
    getCategoryName,
    showSnackMessage,
    toggleExpanded: sharedToggleExpanded
  } = useRulesReview()

  // Auto rules specific state
  const expandedAutoRules = ref(new Set())
  const editingAutoRule = ref(null)
  const ruleFrequencies = ref(new Map())
  const ruleExplanations = ref(new Map())

  // Create rule dialog state
  const showCreateRuleDialog = ref(false)
  const createRuleTransaction = ref(null)
  const createRuleData = ref({
    match_type: 'contains',
    pattern: '',
    category: '',
    labels: []
  })

  // Computed properties
  const effectiveAutoRules = computed(() => {
    if (!props.autoRules || !props.autoRules.rules) return []
    const rules = props.autoRules.rules
      .filter(rule => !rule.applied)
      .map(rule => {
        const transactions = props.ruleMatches.get(rule.id) || []
        const hasInMap = props.ruleMatches.has(rule.id)
        console.log(`effectiveAutoRules: Rule ${rule.id} (${rule.pattern}) has ${transactions.length} transactions, exists in map: ${hasInMap}`)
        return {
          ...rule,
          transactions
        }
      })
    
    console.log('effectiveAutoRules: Total rules with transactions:', rules.length)
    return rules
  })

  // Auto rules specific functions
  const toggleExpanded = (rule) => sharedToggleExpanded(expandedAutoRules, rule)

  function startEditing(rule) {
    editingAutoRule.value = rule.id
  }

  async function saveEdit(rule, editData) {
    try {
      // For auto rules, we need to create a new rule
      const newRule = await api.createRule(editData)
      editingAutoRule.value = null
      showSnackMessage('Rule created successfully')
      // Remove from auto rules list
      remove(rule.id)
      // Emit event to parent to track the new rule
      emit('rule-created', newRule)
      // Emit refresh event to update all components
      emit('refresh-rules')
    } catch (error) {
      console.error('Error creating rule:', error)
      showSnackMessage('Error creating rule: ' + error.message)
    }
  }

  function cancelEdit() {
    editingAutoRule.value = null
  }

  function remove(rule) {
    // Remove from auto rules list (this is just UI state)
    const ruleIndex = props.autoRules.rules.findIndex(r => r.id === rule.id)
    if (ruleIndex !== -1) {
      props.autoRules.rules.splice(ruleIndex, 1)
    }
  }

  // Create rule from transaction
  function createRuleFromTransaction(transaction, rule) {
    createRuleTransaction.value = transaction
    createRuleData.value = {
      match_type: 'contains',
      pattern: transaction.name,
      category: rule.category,
      labels: []
    }
    showCreateRuleDialog.value = true
  }

  function handleCreateRuleSave(ruleData) {
    try {
      console.log('handleCreateRuleSave: Creating rule in memory:', ruleData)
      
      // Create a rule object in memory (don't send to backend yet)
      const newRule = {
        id: `temp_rule_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        ...ruleData,
        priority: 1000, // High priority for user-created rules
        enabled: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        isTemporary: true // Flag to indicate this is not yet saved to backend
      }
      
      console.log('handleCreateRuleSave: Created rule in memory:', newRule)
      showCreateRuleDialog.value = false
      showSnackMessage('Rule created successfully')
      // Emit event to parent to track the new rule
      emit('rule-created', newRule)
    } catch (error) {
      console.error('Error creating rule:', error)
      showSnackMessage('Error creating rule: ' + error.message)
    }
  }

  function cancelCreateRule() {
    showCreateRuleDialog.value = false
    createRuleTransaction.value = null
    createRuleData.value = {
      match_type: 'contains',
      pattern: '',
      category: '',
      labels: []
    }
  }

  // Initialize rule frequencies and explanations
  function initializeRuleData() {
    console.log('initializeRuleData: Called with autoRules:', !!props.autoRules)
    if (props.autoRules && props.autoRules.rules) {
      console.log('initializeRuleData: Processing', props.autoRules.rules.length, 'rules')
      props.autoRules.rules.forEach(rule => {
        ruleFrequencies.value.set(rule.id, rule.frequency || 0)
        ruleExplanations.value.set(rule.id, rule.explain || '')
      })
    }
  }

  // Watch for changes in autoRules and initialize data
  watch(() => props.autoRules, () => {
    initializeRuleData()
  }, { immediate: true })

  return {
    // State
    expandedAutoRules,
    editingAutoRule,
    ruleFrequencies,
    ruleExplanations,
    showCreateRuleDialog,
    createRuleTransaction,
    createRuleData,
    showSnack,
    snackMessage,
    
    // Computed
    effectiveAutoRules,
    
    // Methods
    getCategoryName,
    showSnackMessage,
    toggleExpanded,
    startEditing,
    saveEdit,
    cancelEdit,
    remove,
    createRuleFromTransaction,
    handleCreateRuleSave,
    cancelCreateRule,
    initializeRuleData
  }
}