<template>
  <RulesReview
    title="🤖 Auto-Generated Rules Review"
    :subtitle="`${autoRules?.rules?.length || 0} auto-generated rules suggested based on your transaction patterns.`"
    :rules="effectiveAutoRules"
    rule-type="auto-rule"
    rules-section-class="auto-rules"
    :accounts="accounts"
    :expanded-rules="expandedAutoRules"
    :editing-rule="editingAutoRule"
    :show-create-rule-dialog="showCreateRuleDialog"
    :create-rule-transaction="createRuleTransaction"
    :create-rule-data="createRuleData"
    :show-snack="showSnack"
    :snack-message="snackMessage"
  />
</template>

<script>
import AutoGeneratedRulesReviewJS from './AutoGeneratedRulesReview.js'
import { createRulesReviewComponent } from '../RulesReview.js'

const props = {
  autoRules: Object,
  ruleMatches: {
    type: Map,
    default: () => new Map()
  },
  transactions: Array,
  accounts: Array
}

export default createRulesReviewComponent(
  'AutoGeneratedRulesReview',
  AutoGeneratedRulesReviewJS,
  props
)
</script>
