<template>
  <div class="auto-generated-rules-review">
    <div class="header">
      <h3>🤖 Auto-Generated Rules Review</h3>
      <p class="subtitle">
        {{ autoRules.length}} auto-generated rules suggested based on your transaction patterns.
      </p>
    </div>

    <div v-if="autoRules && autoRules.rules && autoRules.rules.length > 0" class="rules-section auto-rules">

      <!-- Auto Rules List -->
      <div class="rules-list">
        <RuleItem
          v-for="rule in effectiveAutoRules"
          :key="rule.id"
          :rule="rule"
          rule-type="auto-rule"
          :accounts="accounts"
          :is-expanded="expandedAutoRules.has(rule.id)"
          :is-editing="editingAutoRule === rule.id"
          :show-create-rule-button="true"
          @edit="startEditingAutoRule"
          @save-edit="saveAutoRuleEdit"
          @cancel-edit="cancelAutoRuleEdit"
          @remove="removeAutoRule"
          @toggle-expanded="toggleAutoRuleExpanded"
          @create-rule="createRuleFromTransaction"
        />
      </div>
    </div>

    <!-- No Rules Message -->
    <div v-if="(!autoRules || !autoRules.rules || autoRules.rules.length === 0)" class="no-rules">
      <p>No rules were applied or suggested for this import.</p>
    </div>


    <!-- Create Rule Dialog -->
    <CreateRuleDialog
      :show="showCreateRuleDialog"
      :transaction="createRuleTransaction"
      :initial-data="createRuleData"
      @save="handleCreateRuleSave"
      @cancel="cancelCreateRule"
    />

    <!-- Snack Message -->
    <div v-if="showSnack" class="snack-message">
      {{ snackMessage }}
    </div>
  </div>
</template>

<script src="./AutoGeneratedRulesReview.js"></script>
<style scoped src="./AutoGeneratedRulesReview.css"></style>
